# Generated by Django 4.1.3 on 2022-11-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarArchivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='factura',
            field=models.CharField(default='sin datos', max_length=25),
        ),
        migrations.AddField(
            model_name='document',
            name='telefono',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
