# Generated by Django 4.1.3 on 2022-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarArchivos', '0002_document_factura_document_telefono_document_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
