# Generated by Django 4.1.3 on 2022-11-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarArchivos', '0003_alter_document_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='canton',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='direccion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='lugar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='provincia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
