# Generated by Django 4.1.3 on 2022-12-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionarArchivos', '0004_document_canton_document_direccion_document_lugar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='instalacion',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='institucion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='numeroCur',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='personaEncargada',
            field=models.CharField(default='Patricio León', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='rucEmisor',
            field=models.CharField(default='1768152560001', max_length=13),
        ),
    ]
